# --- RISK WEIGHTS (Normalized to sum = 1.0) ---
W_NEW_RECEIVER = 0.35
W_AMOUNT_DEV = 0.30
W_TIME_ANOMALY = 0.20
W_CALL_FLAG = 0.15

# --- THRESHOLDS ---
HIGH_RISK_THRESHOLD = 60
MEDIUM_THRESHOLD = 40

# --- SYSTEM CONFIG ---
DECAY_FACTOR = 0.85
GOLDEN_WINDOW_MINUTES = 20
