import sys
import os
import unittest
from datetime import datetime, timezone

# Add parent directory to path
sys.path.insert(0, os.path.abspath(os.path.join(os.path.dirname(__file__), '..')))

from app.core.data_store import data_store
from app.services.orchestrator import run_pipeline
from app.services.evidence_agent import (
    collect_evidence,
    collect_evidence_for_transaction,
    collect_evidence_for_case
)


class TestEvidenceAgent(unittest.TestCase):

    def setUp(self):
        # Clear data store for isolated testing
        data_store["transactions"].clear()
        data_store["cases"].clear()
        data_store["graphs"].clear()
        data_store["accounts"].clear()
        data_store["actions"].clear()

    def test_missing_data_handling(self):
        """Test that missing transactions/cases return structured package without crashing."""
        result_tx = collect_evidence_for_transaction("TX-NONEXISTENT", data_store)
        self.assertFalse(result_tx["found"])
        self.assertEqual(result_tx["target_id"], "TX-NONEXISTENT")
        self.assertEqual(len(result_tx["evidence"]), 1)
        self.assertIn("not found", result_tx["evidence"][0]["finding"].lower())

        result_case = collect_evidence_for_case("CASE-NONEXISTENT", data_store)
        self.assertFalse(result_case["found"])
        self.assertEqual(result_case["target_id"], "CASE-NONEXISTENT")

    def test_transaction_evidence_extraction(self):
        """Test evidence extraction for a valid transaction."""
        tx = {
            "tx_id": "TX-TEST-001",
            "timestamp": "2026-09-01T10:00:00Z",
            "sender_account": "ACC-USR-1001",
            "receiver_account": "ACC-MULE-9001",
            "amount": 250000.0,
            "currency": "INR",
            "channel": "UPI",
            "on_active_call": True,
            "is_cross_border": True
        }

        pipeline_result = run_pipeline(tx, data_store)
        processed_tx = pipeline_result["transaction"]
        tx_id = processed_tx["tx_id"]

        evidence_pkg = collect_evidence_for_transaction(tx_id, data_store)
        self.assertTrue(evidence_pkg["found"])
        self.assertEqual(evidence_pkg["target_id"], tx_id)
        self.assertGreater(evidence_pkg["summary"]["total_evidence_items"], 0)

        # Check evidence items structure
        for ev in evidence_pkg["evidence"]:
            self.assertIn("id", ev)
            self.assertIn("type", ev)
            self.assertIn("category", ev)
            self.assertIn("severity", ev)
            self.assertIn("finding", ev)
            self.assertIn("data", ev)
            self.assertIn("source", ev)
            # Ensure no speculative/hallucinated terms in findings
            finding_lower = ev["finding"].lower()
            self.assertNotIn("money laundering", finding_lower)
            self.assertNotIn("sanctions", finding_lower)
            self.assertNotIn("guilty", finding_lower)

        # Verify telemetric evidence was captured
        telemetry_ev = next((e for e in evidence_pkg["evidence"] if e["type"] == "behavioral_telemetry"), None)
        self.assertIsNotNone(telemetry_ev)
        self.assertIn("Active voice call", telemetry_ev["finding"])

    def test_case_evidence_extraction(self):
        """Test evidence extraction for a case generated by high-risk transactions."""
        tx1 = {
            "tx_id": "TX-CASE-001",
            "timestamp": "2026-09-01T11:00:00Z",
            "sender_account": "ACC-VICTIM-001",
            "receiver_account": "ACC-MULE-001",
            "amount": 450000.0,
            "currency": "INR",
            "channel": "NEFT",
            "on_active_call": True
        }
        res1 = run_pipeline(tx1, data_store)
        case = res1["case"]
        self.assertIsNotNone(case)
        case_id = case["case_id"]

        # Collect case evidence
        evidence_pkg = collect_evidence_for_case(case_id, data_store)
        self.assertTrue(evidence_pkg["found"])
        self.assertEqual(evidence_pkg["case_id"], case_id)
        self.assertGreaterEqual(evidence_pkg["summary"]["total_evidence_items"], 4)

        # Verify categories present
        types = [ev["type"] for ev in evidence_pkg["evidence"]]
        self.assertIn("case_overview", types)
        self.assertIn("financial", types)
        self.assertIn("transaction", types)
        self.assertIn("graph_network", types)

    def test_no_fabricated_evidence(self):
        """Verify that missing fields do not fabricate external KYC or sanctions data."""
        tx = {
            "tx_id": "TX-CLEAN-001",
            "timestamp": "2026-09-01T12:00:00Z",
            "sender_account": "ACC-REGULAR-1",
            "receiver_account": "ACC-REGULAR-2",
            "amount": 500.0,
            "currency": "INR",
            "channel": "UPI"
        }
        run_pipeline(tx, data_store)
        evidence_pkg = collect_evidence("TX-CLEAN-001", data_store)

        for ev in evidence_pkg["evidence"]:
            data_keys = [k.lower() for k in ev["data"].keys()]
            self.assertNotIn("sanctions_match", data_keys)
            self.assertNotIn("criminal_record", data_keys)
            self.assertNotIn("kyc_external_status", data_keys)
            self.assertNotIn("device_mac_address", data_keys)


if __name__ == "__main__":
    unittest.main()
