import os
import sys
import unittest
import asyncio

sys.path.insert(0, os.path.abspath(os.path.join(os.path.dirname(__file__), '..')))

from app.core.data_store import data_store
from app.engines.graph_engine import build_investigation_graph

class TestAttackModeGraph(unittest.TestCase):
    def setUp(self):
        data_store["graphs"] = {}
        data_store["cases"] = {}
        data_store["transactions"] = {}
        data_store["accounts"] = {}

    def test_01_attack_mode_generates_connected_five_hop_graph(self):
        from main import trigger_attack_mode, get_cases
        from app.repositories.in_memory import InMemoryCaseRepository
        
        # Trigger Attack Mode burst
        res = asyncio.run(trigger_attack_mode())
        self.assertTrue(res.get("ok"))

        # Wait briefly for background task _fire_burst to complete
        asyncio.run(asyncio.sleep(3.0))

        # Retrieve cases using in-memory repository
        repo = InMemoryCaseRepository(data_store)
        cases = asyncio.run(get_cases(repo=repo))
        self.assertGreater(len(cases), 0)


        # Find case generated by attack mode
        attack_case = next((c for c in cases if "ATTACK" in c.get("case_id", "") or any(e.get("pattern_type") == "MULE_CHAIN" for e in c.get("edges", []))), None)
        self.assertIsNotNone(attack_case, "Attack mode case not found in GET /cases payload!")

        case_id = attack_case["case_id"]
        graph = build_investigation_graph(case_id, data_store)

        nodes = graph.get("nodes", [])
        edges = graph.get("edges", [])

        # Assert 6 nodes and 5 edges
        self.assertEqual(len(nodes), 6, f"Expected 6 account nodes in attack chain graph, got {len(nodes)}")
        self.assertEqual(len(edges), 5, f"Expected 5 transaction edges in attack chain graph, got {len(edges)}")

        # Sort edges by hop_number
        sorted_edges = sorted(edges, key=lambda e: e.get("hop_number", 0))

        # Edge continuity assertion: edge1.target == edge2.source, edge2.target == edge3.source, etc.
        for i in range(len(sorted_edges) - 1):
            src_next = sorted_edges[i+1].get("source") or sorted_edges[i+1].get("from")
            tgt_curr = sorted_edges[i].get("target") or sorted_edges[i].get("to")
            self.assertEqual(tgt_curr, src_next, f"Chain discontinuity between hop {i+1} target ({tgt_curr}) and hop {i+2} source ({src_next})")

        # Assert total_hops == 5 for all edges
        for e in edges:
            self.assertEqual(e.get("total_hops"), 5)

        # Assert sorted hop_numbers == [1, 2, 3, 4, 5]
        self.assertEqual([e.get("hop_number") for e in sorted_edges], [1, 2, 3, 4, 5])

        # Assert Node Account Types
        node_types = set(n.get("account_type") for n in nodes)
        self.assertIn("SOURCE", node_types)
        self.assertIn("MULE", node_types)
        self.assertIn("INTERMEDIARY", node_types)
        self.assertIn("DESTINATION", node_types)

if __name__ == "__main__":
    unittest.main()
